kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  clusterIP: None
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  serviceName: "api"
  replicas: 3
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "registry.digitalocean.com/wdc-registry/key-value-app:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: CONFIG_VERSION
              value: "3"
            - name: NODES
              value: "3"
            - name: PREVIOUS_NODES
              value: "2"
            - name: TESTING
              value: "GG!!"
            - name: FILE_PATH_PREFIX
              value: "/data"
            - name: RABBIT_MQ_HOST
              value: "my-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq
                  key: rabbitmq-password

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api-public
  labels:
    app: api-public
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api
