kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: key-value-app-set
spec:
  selector:
    matchLabels:
      app: key-value-app
  serviceName: "key-value-app"
  replicas: 4
  template:
    metadata:
      labels:
        app: key-value-app
    spec:
      containers:
        - name: key-value-app
          image: "registry.digitalocean.com/wdc-registry/key-value-app:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: FILE_PATH_PREFIX
              value: "/data"
            - name: RABBIT_MQ_HOST
              value: "my-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq
                  key: rabbitmq-password

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
