kind: Service
apiVersion: v1
metadata:
  name: api-primary
spec:
  clusterIP: None
  selector:
    app: api-primary
  ports:
    - port: 8080
      targetPort: 8080
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: api-primary
spec:
  selector:
    matchLabels:
      app: api-primary
  serviceName: "api-primary"
  replicas: 1
  template:
    metadata:
      labels:
        app: api-primary
        type: kv-app
    spec:
      containers:
        - name: api-primary
          image: "registry.digitalocean.com/wdc-registry/key-value-app:20"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: NODES
              value: "1"
            - name: FILE_PATH_PREFIX
              value: "/data"
            - name: TESTING
              value: "abcdehdjgfasdasdfdsddf"
            - name: MODE
              value: primary
            - name: RABBIT_MQ_HOST
              value: "my-rabbitmq.default.svc.cluster.local"
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbitmq
                  key: rabbitmq-password

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
