apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: key-value-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: key-value-app
